services:
  traefik:
    image: traefik:v3
    container_name: traefik
    command:
      - "--log.level=DEBUG" 
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.forwardedHeaders.insecure=true"
      - "--entrypoints.websecure.forwardedHeaders.insecure=true"
      - "--certificatesresolvers.lehttp.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.lehttp.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.lehttp.acme.storage=/etc/traefik/acme/acme.json"
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      - DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik-cert:/etc/traefik/acme"
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.18.0.2

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  nextcloud:
    image: nextcloud:31.0.4-apache   
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${DUCKDNS_DOMAIN}
      - OVERWRITECLIURL=https://${DUCKDNS_DOMAIN}
      - TRUSTED_PROXIES=172.18.0.0/16 192.168.88.1
      - TRUSTED_DOMAINS=${DUCKDNS_DOMAIN}
      - NEXTCLOUD__CONFIG__ALLOW_LOCAL_REMOTE_SERVERS=true
      - NEXTCLOUD__CONFIG__MAINTENANCE_WINDOW_START=2   # 02:00 UTC → 04:00–08:00 CEST
    volumes:
      - nc-data:/var/www/html
      - /mnt/ct500mx:/mnt/ct500mx:rw,uid=33,gid=33 # server ssd disk serving as an external storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${DUCKDNS_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=lehttp"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-headers@docker"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsIncludeSubdomains=true"
    extra_hosts:
      - "collabora-elitedock.duckdns.org:172.18.0.2"
      - "elitedock.duckdns.org:172.18.0.2"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  collabora:
    image: collabora/code:24.04.13.3.1
    container_name: collabora
    environment:
      - domain=${DUCKDNS_DOMAIN_REGEX}       # Nextcloud’s FQDN with escaped special signs
      - server_name=${COLLABORA_DOMAIN}      # must match DuckDNS collabora hostname
      - username=${COLLABORA_ADMIN_USER}
      - password=${COLLABORA_PASS}
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true --o:storage.wopi.host=${DUCKDNS_DOMAIN_REGEX} --o:storage.wopi.allowlist=${DUCKDNS_DOMAIN_REGEX}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collabora.rule=Host(`${COLLABORA_DOMAIN}`)"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.routers.collabora.tls=true"
      - "traefik.http.routers.collabora.tls.certresolver=lehttp"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"
    extra_hosts:
      - "elitedock.duckdns.org:172.18.0.2"
    restart: unless-stopped
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:9980/hosting/discovery"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      default:
        ipv4_address: 172.18.0.3

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
  traefik-cert:
  db-data:
  nc-data:
